apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
spec:
  containers:
    - name: todoapp-pod
      image: klptu/todoapp:3.0.0
      readinessProbe:
        httpGet:
          path: /api/ready/
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /api/health/
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 20